### PR TITLE
fix: Iavl upgrade

### PR DESCRIPTION
**Pull request by ZaradarBH**
IAVL 0.19.4 upgrade

### CODE REVIEW

**Comment by ZaradarBH** [comment]
@inon-man I wasnt 100% sure if we where targeting release/v0.45.x or v0.45.x-rebels, so I opted for the canonical one (release/v0.45.x). If I need to retarget let me know and I will do the  needful :)

**Comment by inon-man** [comment]
The mempool priority changes should not be included in this PR. and I think we should skip fast forward upgrade by default because depending on the validator's operating environment, the node may not be restarted again. It seems that the app.toml is missing the additional flag for iavl upgrade.

**Review by inon-man — CHANGES_REQUESTED** [review]
~~iavl upgrade should not be included in this PR~~
Oh sorry wrong issue.

**Comment by ZaradarBH** [comment]
The canonical version of cosmos sdk release/v0.45.x already has the IAVL 0.19.5 upgrade so in a sense this was never needed for anything but the 0.44.x line which I dont really see  a reason to patch since we are scheduled to release 2.0.4 at the end of Q1. @inon-man @nghuyenthevinh2000 what do you think about this?

**Pull request closed without merging**
